/**
 * Created by kako on 2016/03/04.
 */

var PP2_LANGUAGE = (function() {
    var define = {
        ja: {
            connecting_to_format: "データの準備をしています",
            connected_to_format: "%sに接続しています",
            songs: "曲",
            digiscorelite: "デジスコア・ライト",
            rhythm: "リズム",
            flashcard: "フラッシュ・カード",
            remote_controller: "リモコン",
            songs_title: "曲",
            rhythm_title: "リズム",
            tempo: "テンポ",
            digiscorelite_settings: "デジスコア・ライト設定",
            auto_page_turn: "自動譜めくり",
            page_turn: "ペダルによる譜めくり",
            style: "スタイル",
            beat: "拍子",
            bpm: "テンポ",
            start: "スタート",
            start_camelcase: "スタート",
            stop: "ストップ",
            variation: "バリエーション",
            auto_fill: "オートフィルイン",
            intro: "イントロ",
            ending: "エンディング",
            sync_start: "シンク・スタート",
            only_drums: "ドラムのみ",
            rhythm_settings: "リズム設定",
            start_stop_by_pedal: "ペダルでのスタート/ストップ",
            on: "オン",
            off: "オフ",
            offset_interval: "譜めくりのタイミング",
            chord_recognition_type: "コード認識タイプ",
            standard: "スタンダード",
            intelligent: "インテリジェント",
            pianist: "ピアニスト",
            left_pedal: "左ペダル",
            center_pedal: "中央ペダル",
            bass_inversion: "リーディング・ベース",
            tone_settings: "音色設定",
            tones: "音色",
            left: "左",
            right: "右",
            tone1: "音色1",
            tone2: "音色2",
            keyboard_settings: "鍵盤設定",
            single: "シングル",
            split: "スプリット",
            dual: "デュアル",
            twin_piano: "ツイン ピアノ",
            split_point: "スプリット・ポイント",
            balance: "バランス",
            right_shift: "右手シフト",
            left_shift: "左手シフト",
            tone1_shift: "音色 1 シフト",
            tone2_shift: "音色 2 シフト",
            individual: "セパレート",
            pair: "ペア",
            information: "インフォメーション",
            connected_to: "接続しているピアノ",
            version: "バージョン",
            visit_us: "Webサイト",
            special_thanks_to: "スペシャルサンクス",
            here: "こちら",
            license: "ライセンス",
            software_license: "ソフトウェア・ライセンス",
            settings: "設定",
            connection: "接続",
            bluetooth_midi_device: "Bluetooth MIDI デバイス",
            initialize_app_settings: "アプリ設定の初期化",
            initialize: "初期化",
            sure_you_want: "本当によろしいですか？",
            initialize_finished: "初期化しました",
            initialize_failed: "初期化に失敗しました",
            not_connected: "未接続",
            yes: "はい",
            no: "いいえ",
            not_show_yes: 'はい',
            not_show_no: 'いいえ',
            song_cannot_diplay_song: "この楽曲は表示できません。",
            digiscore_cannot_diplay_song: "譜面表示できません。",
            flashcard_select_mode: "もーどを えらんでね",
            flashcard_mode_listen: "おとをきいてあてる",
            flashcard_mode_read: "おんぷをみてあてる",
            flashcard_beginner: "かんたん",
            flashcard_average: "ふつう",
            flashcard_expert: "むずかしい",
            flashcard_start: "はじめる",
            flashcard_listen_to_reference: "きじゅんの ド のおとを ききましょう",
            flashcard_listen_again: "もういちどきく",
            flashcard_next: "つぎへ",
            flashcard_reset: "はじめから",
            flashcard_question: "もんだい",
            flashcard_answer: "あなたのこたえ",
            flashcard_guess_and_play: "きこえたおとと おなじおとを ひいてね",
            flashcard_lets_play: "おなじおとを ひいてね",
            flashcard_heigher: "もっと たかい おとだよ",
            flashcard_lower: "もっと ひくい おとだよ",
            flashcard_right: "せいかい!",
            flashcard_wrong: "まちがい!",
            flashcard_timeup: "じかんぎれ!",
            flashcard_point: "てん",
            flashcard_comment_excellent: "すばらしい！",
            flashcard_comment_welldone: "よくできました",
            flashcard_comment_good: "なかなかいいぞ！",
            flashcard_comment_notbad: "もうひといき！",
            flashcard_comment_bad: "もっとれんしゅうしてね",
            flashcard_try_again: "もういちど",
            flashcard_check: "とくてん",
            key_touch: "キー・タッチ",
            key_touch_fix: "固定",
            key_touch_super_light: "非常に軽い",
            key_touch_light: "軽い",
            key_touch_medium: "普通",
            key_touch_heavy: "重い",
            key_touch_super_heavy: "非常に重い",
            metronome_settings: "メトロノーム設定",
            metronome: "メトロノーム",
            metronome_tempo: "テンポ",
            metronome_pattern: "パターン",
            metronome_beat: "拍子",
            metronome_down_beat: "強拍",
            metronome_volume: "メトロノーム音量",
            metronome_tone: "音色",
            metronome_tone_click: "クリック",
            metronome_tone_electronic: "電子音",
            metronome_tone_voice_jp: "いちに",
            metronome_tone_voice_en: "One Two",
            keyboard_and_tones_settings: "鍵盤と音色設定",
            overall_settings: "全体設定",
            master_tuning: "マスターチューニング",
            ambience: "音の響き",
            headphones_3d_ambience: "ヘッドホン3Dアンビエンス",
            reverb_level: "音の響き",
            brilliance: "音の明るさ",
            song_transpose: "曲のトランスポーズ",
            keyboard_transpose: "鍵盤のトランスポーズ",
            transpose: "トランスポーズ",
            transpose_mode: "トランスポーズ・モード",
            transpose_mode_keyboard_and_song: "鍵盤+曲",
            transpose_mode_keyboard: "鍵盤のみ",
            transpose_mode_song: "曲のみ",
            reset: "リセット",
            close: "閉じる",
            error_disconnected: "MIDIデバイス切断",
            error_disconnected_message: "ピアノとの接続が切断されました[E004]",
            error_acquisition: "データ取得エラー",
            error_acquisition_message_download_failed: "データの取得に失敗しました[E003]",
            error_acquisition_message_unzip_failed: "データの取得に失敗しました[E005]",
            error_acquisition_message_unknown: "データの取得に失敗しました[E999]",
            error_network_message: "ネットワークへの接続が必要です[E002]",
            error_connect_failed: "MIDIデバイス接続エラー",
            error_connect_failed_message: "ピアノとの接続に失敗しました[E001]",
            error_user_login_failed: "ログインできませんでした",
            master_volume: "ピアノ音量",
            songs_settings: "曲設定",
            flashcard_settings: "フラッシュ・カード設定",
            diary: "ダイアリー",
            diary_played_piano: "ピアノを%d時間 %d分弾きました",
            diary_played_piano_without_hour: "ピアノを%d分弾きました",
            diary_not_played_piano: "今日は、ピアノを弾いていません",
            diary_activity_log: "活動の履歴",
            diary_song_list: "フレーズ",
            diary_count_per_key: "鍵盤",
            diary_count_per_time: "時間",
            today: "今日",
            users: "ユーザ",
            create_user: "ユーザーの追加",
            create_user_cancel: '戻る',
            create_user_back: '戻る',
            create_user_next: '次へ',
            create_user_finish: '完了',
            create_user_reset_password_message: 'アカウントに対して、前回ご設定いただいたパスワードと今回ご設定いただいたパスワードが異なっているため、もう一度認証が必要です。\nメールアドレス(%s)にお送りした認証コードを入力してください。',
            edit_user: "ユーザーの編集",
            edit_user_cancel: '戻る',
            edit_user_back: '戻る',
            edit_user_next: '次へ',
            edit_user_finish: '変更する',
            recorder: "レコーダー",
            cancel: "キャンセル",
            back: "戻る",
            next: "次へ",
            submit: "送信",
            user_email: 'メールアドレス',
            user_email_confirm: 'メールアドレス（確認）',
            user_password: 'パスワード',
            user_password_confirm: 'パスワード（確認）',
            user_old_password: '現在のパスワード',
            user_new_password: 'パスワード',
            user_new_password_confirm: 'パスワード（確認）',
            user_verification_code: '認証コード',
            user_handle_name: 'ハンドルネーム',
            user_agree_terms: 'プライバシーポリシーに同意する',
            user_save_data_to_server: 'データをサーバに保存',
            user_first_day_of_a_week: '週の始まり',
            user_sunday: '日曜日',
            user_monday: '月曜日',
            user_icon: 'アイコン',
            user_select_icon: '選択',
            user_sure_register: '登録してもよろしいですか？',
            user_verification_code_message: '入力いただいたメールアドレス(%s)に認証コード（Verification Code）を送信しました。\n届いていない場合は「verificationemail.com」からのメールを受信できるよう設定してください。',
            user_resend_verification_code: '認証コードを再送する',
            user_resend_verification_code_finished: '認証コードを再送しました',
            user_term: 'Piano Partner 2に、お客様の個人情報、お客様自身で録音したデータ、フレーズデータ、設定データ等（以下、「個人情報等」といいます。）を登録するに当たり、お客様は、以下の事項に同意したものとします。\n\n■ 個人情報等の利用目的\n当社は、お客様の個人情報等を以下の目的の範囲内でのみ利用します。\n・お客様のご利用状況の把握\n・製品の企画・開発・改良\n\n■ 個人情報等の保存場所とクラウドサーバのホスティング(サービスプロバイダ)について\nPiano Partner 2に登録したお客様の個人情報等は、米国のオレゴン州に所在するAmazon Web Services(AWS)でホスティングされ構成されたクラウドサーバに転送され、現地の法律およびAWSの規約に基づき、保存、処理されます。\n\nAWSの規約については、<a href="#" onclick="PP2_CORE.openInBrowser(\'https://aws.amazon.com/jp/privacy/\');">ここ</a>を参照ください。\n\n■ その他\n本文に記載のない事項については、ローランド株式会社の<a href="#" onclick="PP2_CORE.openInBrowser(\'https://www.roland.com/jp/privacy/\');">プライバシーポリシー</a>をご確認下さい。',
            user_data_migration: 'データの引き継ぎ',
            user_data_migration_message: 'レコーダー / ダイアリーのデータを他の端末から、引き継ぎます',
            user_data_migration_transfer: 'データを引き継ぐ',
            user_data_migration_forgot_password: 'Passwordをわすれた',
            user_data_migration_cancel: 'もどる',
            user_forgot_password_complete: 'パスワードを再設定しました。',
            user_reset_password: 'パスワード再設定',
            user_reset_password_cancel: 'もどる',
            user_reset_password_submit: 'パスワードを再設定',
            user_force_change_email_button: 'メールアドレスの変更',
            user_edit_input_if_needed: '変更したい項目を入力してください',
            user_edit_confirm: '設定の更新を行います',
            user_edit_complete: '設定の更新を行いました',
            share: 'シェア',
            share_message: '%s ピアノを%d時間 %d分弾きました。合計%d音弾きました。',
            share_message_without_hour: '%s ピアノを%d分弾きました。合計%d音弾きました。',
            share_message_not_played: '%s 今日は、ピアノを弾いていません。',
            confirm_remove_manual_recorded_song: '録音した曲を消すと、元には戻せません\n本当に消しますか?',
            confirm_remove_auto_recorded_song: '自動録音したフレーズを消すと、元には戻せません\n本当に消しますか?',
            confirm_move_to_recorder: 'この自動録音したフレーズを、「レコーダー」に移しますか?',
            confirm_change_user: 'ユーザーを切り替えますか?',
            confirm_ok: 'はい',
            confirm_ok_delete: 'はい',
            confirm_ok_switch: '切り替える',
            confirm_cancel: 'もどる',
            alert_close: "とじる",
            prompt_submit: '決定',
            enquete: 'アンケート',
            enquete_blank: '任意回答',
            enquete_age: '年齢は?',
            enquete_age_1: 'Under 5',
            enquete_age_2: '6-12',
            enquete_age_3: '13-17',
            enquete_age_4: '18-24',
            enquete_age_5: '25-34',
            enquete_age_6: '35-44',
            enquete_age_7: '45-54',
            enquete_age_8: '55-64',
            enquete_age_9: '65-74',
            enquete_age_10: '75+',
            enquete_piano_performance: 'ピアノは弾けますか?',
            enquete_piano_performance_1: 'はい',
            enquete_piano_performance_2: '片手なら',
            enquete_piano_performance_3: 'いいえ',
            enquete_length_of_experience: '演奏経験は、どれくらいですか?',
            enquete_length_of_experience_1: '一年未満',
            enquete_length_of_experience_2: '1 - 5 年',
            enquete_length_of_experience_3: '6 - 10 年',
            enquete_length_of_experience_4: '10 - 20 年',
            enquete_length_of_experience_5: '20 年以上',
            rhythm_notification_message: 'Android端末でBluetooth接続時にリズム、ダイアリー、レコーダー機能を使うと、演奏に不自然さを感じる場合があります。\nUSBケーブルによる有線接続にてご使用ください。',
            rhythm_notification_not_show_again: '次回から、この表示を行わない',
            cognito_error_need_password_reset: 'メールアドレス(%s) はパスワード再設定が必要です。',
            cognito_error_network_error: 'ネットワークに繋がっていません。',
            cognito_error_already_exists: 'このメールアドレスは既に登録されています。',
            cognito_error_code_mismatch: '認証コードが正しくありません。',
            cognito_error_others_when_registration: '登録に失敗しました',
            cognito_error_others_when_update: '更新に失敗しました',
            cognito_error_others_when_login: '認証に失敗しました',
            cognito_error_others_when_forgot_password: 'パスワード再設定用認証コードの送信に失敗しました',
            cognito_error_user_modified_by_other_device: '別の端末から設定が更新されたため、更新処理を中断します',
            guest_notification_message: 'ダイアリーの内容は1ヶ月経つと消えてゆきます。\nユーザーの追加を行うことで、一ヶ月よりも前のダイアリーをみたり、お使いの端末のデータを引き継ぐことができるようになります。',
            guest_notification_not_show_again: '次回から、この表示を行わない',
            guest_notification_create_now: 'ユーザーの追加を行う',
            guest_notification_not_create_now: '今は、ユーザー追加を行わない',
            email_verification_message: 'アカウントの認証が必要です。\nメールアドレス(%s)に、送った認証コードを入力してください。',
            communicating_with_the_server: 'サーバーと通信を行っています',
            device_storage_notification_message: "端末の空き容量が少なくなっています。"
        },
        en: {
            connecting_to_format: "Preparing Data",
            connected_to_format: "Connected to %s",
            songs: "Songs",
            digiscorelite: "DigiScore Lite",
            rhythm: "Rhythms",
            flashcard: "Flash Cards",
            remote_controller: "Remote Controller",
            songs_title: "SONGS",
            rhythm_title: "RHYTHMS",
            tempo: "Tempo",
            digiscorelite_settings: "DigiScore Lite Settings",
            auto_page_turn: "Auto Page Turn",
            page_turn: "Page turn by Pedal",
            style: "STYLES",
            beat: "BEAT",
            bpm: "BPM",
            start: "START",
            start_camelcase: "Start",
            stop: "STOP",
            variation: "VARIATION",
            auto_fill: "AUTO FILL",
            intro: "Intro",
            ending: "Ending",
            sync_start: "SYNC START",
            only_drums: "Only Drums",
            rhythm_settings: "Rhythm Settings",
            start_stop_by_pedal: "Start/Stop by Pedal",
            left_pedal: "Left Pedal",
            center_pedal: "Center Pedal",
            bass_inversion: "Leading Bass",
            on: "On",
            off: "Off",
            offset_interval: "Timing of Page turn",
            chord_recognition_type: "Chord Recognition Type",
            standard: "STANDARD",
            intelligent: "INTELLIGENT",
            pianist: "PIANIST",
            tone_settings: "TONES",
            tones: "TONES",
            left: "Left",
            right: "Right",
            tone1: "Tone1",
            tone2: "Tone2",
            keyboard_settings: "KEYBOARD",
            single: "Single",
            split: "Split",
            dual: "Dual",
            twin_piano: "Twin Piano",
            split_point: "Split Point",
            balance: "Balance",
            right_shift: "Right Shift",
            left_shift: "Left Shift",
            tone1_shift: "Tone 1 Shift",
            tone2_shift: "Tone 2 Shift",
            individual: "Individual",
            pair: "Pair",
            information: "INFORMATION",
            connected_to: "Connected to",
            version: "Version",
            visit_us: "Web Site",
            special_thanks_to: "Special thanks to",
            here: "Here",
            license: "License",
            software_license: "Software License",
            settings: "SETTINGS",
            connection: "Connection",
            bluetooth_midi_device: "Bluetooth MIDI Device",
            initialize_app_settings: "Initialize App Settings",
            initialize: "Initialize",
            sure_you_want: "Are you sure you want?",
            initialize_finished: "Initialize finished.",
            initialize_failed: "Initialize failed.",
            not_connected: "Not connected",
            yes: "Yes",
            no: "No",
            not_show_yes: 'No',
            not_show_no: 'Yes',
            song_cannot_diplay_song: "This song cannot be displayed.",
            digiscore_cannot_diplay_song: "The notation cannot be displayed.",
            flashcard_select_mode: "Select Mode",
            flashcard_mode_listen: "Listen to Sounds",
            flashcard_mode_read: "Read Notations",
            flashcard_beginner: "Beginner",
            flashcard_average: "Average",
            flashcard_expert: "Expert",
            flashcard_start: "Start",
            flashcard_listen_to_reference: "Listen to the reference note C:",
            flashcard_listen_again: "Listen again",
            flashcard_next: "Next",
            flashcard_reset: "Reset",
            flashcard_question: "Question!",
            flashcard_answer: "Your answer?",
            flashcard_guess_and_play: "Guess and play the keys I play.",
            flashcard_lets_play: "Let's Play",
            flashcard_heigher: "Try a higher note.",
            flashcard_lower: "Try a lower note.",
            flashcard_right: "Right!",
            flashcard_wrong: "Wrong!",
            flashcard_timeup: "Time's Up!",
            flashcard_point: "Point",
            flashcard_comment_excellent: "Wow! Excellent.",
            flashcard_comment_welldone: "Well done!",
            flashcard_comment_good: "Pretty good.",
            flashcard_comment_notbad: "Not bad.",
            flashcard_comment_bad: "Keep practicing!",
            flashcard_try_again: "Try again",
            flashcard_check: "Check",
            key_touch: "Key Touch",
            key_touch_fix: "Fix",
            key_touch_super_light: "SuperLight",
            key_touch_light: "Light",
            key_touch_medium: "Medium",
            key_touch_heavy: "Heavy",
            key_touch_super_heavy: "SuperHeavy",
            metronome_settings: "METRONOME",
            metronome: "Metronome",
            metronome_tempo: "Tempo",
            metronome_pattern: "Pattern",
            metronome_beat: "Beat",
            metronome_down_beat: "Down Beat",
            metronome_volume: "Metronome Volume",
            metronome_tone: "Tone",
            metronome_tone_click: "Click",
            metronome_tone_electronic: "Electronic",
            metronome_tone_voice_jp: "Voice(Japanese)",
            metronome_tone_voice_en: "Voice(English)",
            keyboard_and_tones_settings: "KEYBOARD and TONES",
            overall_settings: "SETTINGS",
            master_tuning: "Master Tuning",
            ambience: "Ambience",
            headphones_3d_ambience: "Headphones 3D Ambience",
            reverb_level: "Reverb Level",
            brilliance: "Brilliance",
            song_transpose: "Song Transpose",
            keyboard_transpose: "Keyboard Transpose",
            transpose: "Transpose",
            transpose_mode: "Transpose Mode",
            transpose_mode_keyboard_and_song: "Keyboard & Song",
            transpose_mode_keyboard: "Keyboard",
            transpose_mode_song: "Song",
            reset: "Reset",
            close: "Close",
            error_disconnected: "MIDI device disconnected",
            error_disconnected_message: "Connection with the piano has been lost.[E004]",
            error_acquisition: "Acquisition Error",
            error_acquisition_message_download_failed: "Data acquisition has failed[E003]",
            error_acquisition_message_unzip_failed: "Data acquisition has failed[E005]",
            error_acquisition_message_unknown: "Data acquisition has failed[E999]",
            error_network_message: "Need to connect network[E002]",
            error_connect_failed: "MIDI device connection error",
            error_connect_failed_message: "Can not be connected to the piano.[E001]",
            error_user_login_failed: "Login failed.",
            master_volume: "Master Volume",
            songs_settings: "Songs Settings",
            flashcard_settings: "Flash Cards Settings",
            diary: "Diary",
            diary_played_piano: "%d hours and %d minutes you have played the piano.",
            diary_played_piano_without_hour: "%d minutes you have played the piano.",
            diary_not_played_piano: "You don't play the piano today.",
            diary_activity_log: "Activity Log",
            diary_song_list: "Phrase",
            diary_count_per_key: "Keys",
            diary_count_per_time: "Hours",
            today: "Today",
            users: "USERS",
            create_user: "Create new account",
            create_user_cancel: 'Cancel',
            create_user_back: 'Back',
            create_user_next: 'Next',
            create_user_finish: 'Finish',
            create_user_reset_password_message: 'An verification step is required again because the password you set for the account last time is different from the one you set this time.\nPlease enter the verification code sent to the mail address (%s).',
            edit_user: "Edit account",
            edit_user_cancel: 'Cancel',
            edit_user_back: 'Back',
            edit_user_next: 'Next',
            edit_user_finish: 'Finish',
            recorder: "Recorder",
            cancel: "Cancel",
            back: "Back",
            next: "Next",
            submit: "Submit",
            user_email: 'Email',
            user_email_confirm: 'Re-enter email',
            user_password: 'Password',
            user_password_confirm: 'Re-enter password',
            user_old_password: 'Current password',
            user_new_password: 'Password',
            user_new_password_confirm: 'Re-enter password',
            user_verification_code: 'Verification Code',
            user_handle_name: 'User name',
            user_agree_terms: 'I agree to the privacy policy.',
            user_save_data_to_server: 'Save data to server',
            user_first_day_of_a_week: 'The first day of a week',
            user_sunday: 'Sunday',
            user_monday: 'Monday',
            user_icon: 'Icon',
            user_select_icon: 'Select',
            user_sure_register: 'Are you sure you want to register?',
            user_verification_code_message: 'A verification code has been sent to the email address (%s).\nIf you have not received the e-mail, please check your spam filter. To ensure future emails reach your inbox, please add “verificationemail.com” to your email whitelist.',
            user_resend_verification_code: 'Resend verification Code',
            user_resend_verification_code_finished: 'An verification code has been resent.',
            user_term: 'You are considered to have agreed to the following in registering your personal information, your data recorded, your phrase data, settings and others (collectively the “Data”) in Piano Partner 2.\n\n■ Purposes for using the Data\nThe Data is used only for the purpose of;\nⅰ）confirming your status and usage conditions.\nⅱ）planning, developing and improving our products and services.\n\n\n■ Data Location and cloud server hostings (services provider) \n\nThe Data is transferred to the cloud server(the “Server”) hosted and configured by Amazon Web Services (“AWS”) located in Oregon, USA, stored and processed on the Server in accordance with the Federal Law and the State Law, and AWS privacy statement.\n\nThe AWS privacy statement can be found <a href="#" onclick="PP2_CORE.openInBrowser(\'https://aws.amazon.com/privacy/\');">here</a>.\n\n■ Others\nPlease refer to the <a href="#" onclick="PP2_CORE.openInBrowser(\'https://www.roland.com/global/privacy/\');">Privacy Policy</a> of Roland Corporation for the matters not mentioned in this notice.',
            user_data_migration: 'Transfer',
            user_data_migration_message: 'Transfer the recorded data and activity log in diary from another device.',
            user_data_migration_transfer: 'Transfer',
            user_data_migration_forgot_password: 'Forgot password',
            user_data_migration_cancel: 'Cancel',
            user_forgot_password_complete: 'Password reset completed.',
            user_reset_password: 'Reset password',
            user_reset_password_cancel: 'Cancel',
            user_reset_password_submit: 'Reset',
            user_force_change_email_button: 'Change email',
            user_edit_input_if_needed: 'Please enter the item you want to change.',
            user_edit_confirm: 'Do you want to update it?',
            user_edit_complete: 'The update has been completed.',
            share: 'Share',
            share_message: 'On %s, %d hours and %d minutes I have played the piano. I have played a total of %d keys.',
            share_message_without_hour: 'On %s, %d minutes I have played the piano. I have played a total of %d keys.',
            share_message_not_played: 'On %s, I don\'t play the piano today.',
            confirm_remove_manual_recorded_song: 'This recorded song will be permanently deleted.\nAre you sure?',
            confirm_remove_auto_recorded_song: 'This recorded phrase will be permanently deleted.\nAre you sure?',
            confirm_move_to_recorder: 'Would you like to move this automatically recorded phrase to "Recorder"?',
            confirm_change_user: 'Would you like to switch accounts?',
            confirm_ok: 'OK',
            confirm_ok_delete: 'Delete',
            confirm_ok_switch: 'Switch',
            confirm_cancel: 'Cancel',
            alert_close: "Close",
            prompt_submit: 'Ok',
            enquete: 'questionnaire',
            enquete_blank: ' ',
            enquete_age: 'How old are you?',
            enquete_age_1: 'Under 5',
            enquete_age_2: '6-12',
            enquete_age_3: '13-17',
            enquete_age_4: '18-24',
            enquete_age_5: '25-34',
            enquete_age_6: '35-44',
            enquete_age_7: '45-54',
            enquete_age_8: '55-64',
            enquete_age_9: '65-74',
            enquete_age_10: '75+',
            enquete_piano_performance: 'Can you play the piano?',
            enquete_piano_performance_1: 'Yes',
            enquete_piano_performance_2: 'By one hand only',
            enquete_piano_performance_3: 'No',
            enquete_length_of_experience: 'How long have you been playing piano?',
            enquete_length_of_experience_1: 'Under a year',
            enquete_length_of_experience_2: '1-5 years',
            enquete_length_of_experience_3: '6-10 years',
            enquete_length_of_experience_4: '10-20 years',
            enquete_length_of_experience_5: '20+ years',
            rhythm_notification_message: 'When an Android device is connected to the piano via Bluetooth, the performance with using Rhythm, Diary and Recorder functions may not go smoothly.\nIn that case, please connect the device to the piano via USB cables.',
            rhythm_notification_not_show_again: 'Do not show this again.',
            cognito_error_need_password_reset: 'This account(%s) is required to reset the password.',
            cognito_error_network_error: 'Network Failure.',
            cognito_error_already_exists: 'This Email is already exists.',
            cognito_error_code_mismatch: 'Verification code is wrong.',
            cognito_error_others_when_registration: 'Registration failed.',
            cognito_error_others_when_update: 'Update failed.',
            cognito_error_others_when_login: 'Authentication failed.',
            cognito_error_others_when_forgot_password: 'Send password reset verification code failed.',
            cognito_error_user_modified_by_other_device: 'Since the setting was updated from another terminal, we stop the updating process.',
            guest_notification_message: 'Activity logs more than 1 month before will be automatically deleted. \nBy creating account it is possible to view diary more than 1 month before and transfer your data to your new mobile device.',
            guest_notification_not_show_again: 'Do not show this again.',
            guest_notification_create_now: 'Create new account',
            guest_notification_not_create_now: 'Not now',
            email_verification_message: 'Account verification is required.\nPlease enter the verification code sent to the mail address (%s).',
            communicating_with_the_server: 'Communicating with the server.',
            device_storage_notification_message: "There’s not enough free space on your device."
        }
    };
    var language = "ja";
    var songToneLanguage = undefined; // 0:en 1:ja
    return {
        language: language,
        isJa: function() {
            return language == "ja";
        },
        isSongToneLanguageJa: function() {
            return !PP2_CONTENTS.isLanguageSettingAvailable() ? this.isJa() : songToneLanguage == 1;
        },
        setSongToneLanguage: function(value) {
            songToneLanguage = value;
        },
        requestLanguage: function() {
            var self = this;
            PP2_CORE.nativeCallbacks[PP2_CORE.nativeMethods.requestLanguage] = function(lang) {
                language = lang;
                self.reload();
            };
            PP2_CORE.call(PP2_CORE.nativeMethods.requestLanguage);
        },
        setLanguage: function (newLang) {
            language = newLang;
            this.reload();
        },
        reload: function() {
            $('lang').each(function () {
                var key = $(this).attr('key');
                $(this).html(define[language][key]);
            });
        },
        getValues: function() {
            return define[language];
        },
        reset: function() {
            songToneLanguage = undefined;
        }
    };
})();
